-- ============================================================================
-- CaysonElectric Unified Database Schema
-- ============================================================================
-- This file contains the complete database schema for the CaysonElectric
-- educational platform. It includes all tables, foreign keys, indexes,
-- RLS policies, and triggers.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Extensions & Functions
-- ----------------------------------------------------------------------------

-- Enable UUID extension for user ID management
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- ----------------------------------------------------------------------------
-- Drop Existing Tables (for clean reset)
-- ----------------------------------------------------------------------------

DROP TABLE IF EXISTS book_orders CASCADE;
DROP TABLE IF EXISTS applications CASCADE;
DROP TABLE IF EXISTS course_sessions CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- ----------------------------------------------------------------------------
-- Table: profiles
-- ----------------------------------------------------------------------------
-- User profiles linked to Supabase Auth
-- Each authenticated user has exactly one profile

CREATE TABLE profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    zonecode TEXT,
    address TEXT,
    detail_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for profiles
CREATE INDEX IF NOT EXISTS profiles_username_idx ON profiles(username);
CREATE INDEX IF NOT EXISTS profiles_email_idx ON profiles(email);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Table: courses
-- ----------------------------------------------------------------------------
-- Educational programs/courses offered by CaysonElectric

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT, -- e.g., "Certification", "Practical"
    description TEXT,
    price INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for courses
CREATE INDEX IF NOT EXISTS courses_is_active_idx ON courses(is_active);
CREATE INDEX IF NOT EXISTS courses_category_idx ON courses(category);

-- ----------------------------------------------------------------------------
-- Table: course_sessions
-- ----------------------------------------------------------------------------
-- Specific scheduled sessions for courses

CREATE TABLE course_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    time_info TEXT, -- e.g., "Sat/Sun 10:00-17:00"
    capacity INTEGER DEFAULT 20,
    location TEXT,
    status TEXT DEFAULT 'recruiting', -- recruiting, closing-soon, closed, finished
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for course_sessions
CREATE INDEX IF NOT EXISTS course_sessions_course_id_idx ON course_sessions(course_id);
CREATE INDEX IF NOT EXISTS course_sessions_start_date_idx ON course_sessions(start_date);
CREATE INDEX IF NOT EXISTS course_sessions_status_idx ON course_sessions(status);

-- ----------------------------------------------------------------------------
-- Table: applications
-- ----------------------------------------------------------------------------
-- Student enrollment applications for course sessions

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES course_sessions(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    applicant_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    depositor_name TEXT,
    amount INTEGER DEFAULT 0,
    status TEXT DEFAULT 'pending_payment', -- pending_payment, paid, cancelled
    memo TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for applications
CREATE INDEX IF NOT EXISTS applications_session_id_idx ON applications(session_id);
CREATE INDEX IF NOT EXISTS applications_user_id_idx ON applications(user_id);
CREATE INDEX IF NOT EXISTS applications_status_idx ON applications(status);
CREATE INDEX IF NOT EXISTS applications_submitted_at_idx ON applications(submitted_at DESC);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_applications_updated_at ON applications;
CREATE TRIGGER update_applications_updated_at
    BEFORE UPDATE ON applications
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Table: leads
-- ----------------------------------------------------------------------------
-- Contact form submissions and inquiries

CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    topic TEXT DEFAULT 'General Inquiry',
    company TEXT,
    contact_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    message TEXT,
    password TEXT, -- For non-authenticated access
    status TEXT DEFAULT 'new', -- new, in_progress, closed
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for leads
CREATE INDEX IF NOT EXISTS leads_user_id_idx ON leads(user_id);
CREATE INDEX IF NOT EXISTS leads_email_idx ON leads(email);
CREATE INDEX IF NOT EXISTS leads_status_idx ON leads(status);
CREATE INDEX IF NOT EXISTS leads_submitted_at_idx ON leads(submitted_at DESC);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_leads_updated_at ON leads;
CREATE TRIGGER update_leads_updated_at
    BEFORE UPDATE ON leads
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Table: posts
-- ----------------------------------------------------------------------------
-- Resources board for educational materials and announcements

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    content TEXT,
    author_name TEXT DEFAULT 'Admin',
    file_url TEXT, -- URL to uploaded file in Supabase Storage
    views INTEGER DEFAULT 0,
    is_secret BOOLEAN DEFAULT FALSE,
    password TEXT, -- Optional for secret posts
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for posts
CREATE INDEX IF NOT EXISTS posts_author_id_idx ON posts(author_id);
CREATE INDEX IF NOT EXISTS posts_created_at_idx ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS posts_is_secret_idx ON posts(is_secret);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at
    BEFORE UPDATE ON posts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Table: book_orders
-- ----------------------------------------------------------------------------
-- Book orders for publishing service

CREATE TABLE book_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    book_title TEXT NOT NULL,
    quantity INTEGER DEFAULT 1,
    total_price INTEGER DEFAULT 0,
    recipient_name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    email TEXT,
    order_date TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'ordered', -- ordered, shipping, delivered, cancelled
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for book_orders
CREATE INDEX IF NOT EXISTS book_orders_user_id_idx ON book_orders(user_id);
CREATE INDEX IF NOT EXISTS book_orders_email_idx ON book_orders(email);
CREATE INDEX IF NOT EXISTS book_orders_status_idx ON book_orders(status);
CREATE INDEX IF NOT EXISTS book_orders_order_date_idx ON book_orders(order_date DESC);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_book_orders_updated_at ON book_orders;
CREATE TRIGGER update_book_orders_updated_at
    BEFORE UPDATE ON book_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Row Level Security (RLS) Policies
-- ============================================================================

-- ----------------------------------------------------------------------------
-- RLS: profiles
-- ----------------------------------------------------------------------------

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
CREATE POLICY "Users can view own profile"
    ON profiles FOR SELECT
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
CREATE POLICY "Users can insert own profile"
    ON profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile"
    ON profiles FOR UPDATE
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can delete own profile" ON profiles;
CREATE POLICY "Users can delete own profile"
    ON profiles FOR DELETE
    USING (auth.uid() = id);

-- ----------------------------------------------------------------------------
-- RLS: courses
-- ----------------------------------------------------------------------------

ALTER TABLE courses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view courses" ON courses;
CREATE POLICY "Anyone can view courses"
    ON courses FOR SELECT
    USING (TRUE);

DROP POLICY IF EXISTS "Authenticated users can insert courses" ON courses;
CREATE POLICY "Authenticated users can insert courses"
    ON courses FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can update courses" ON courses;
CREATE POLICY "Authenticated users can update courses"
    ON courses FOR UPDATE
    USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can delete courses" ON courses;
CREATE POLICY "Authenticated users can delete courses"
    ON courses FOR DELETE
    USING (auth.role() = 'authenticated');

-- ----------------------------------------------------------------------------
-- RLS: course_sessions
-- ----------------------------------------------------------------------------

ALTER TABLE course_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view sessions" ON course_sessions;
CREATE POLICY "Anyone can view sessions"
    ON course_sessions FOR SELECT
    USING (TRUE);

DROP POLICY IF EXISTS "Authenticated users can insert sessions" ON course_sessions;
CREATE POLICY "Authenticated users can insert sessions"
    ON course_sessions FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can update sessions" ON course_sessions;
CREATE POLICY "Authenticated users can update sessions"
    ON course_sessions FOR UPDATE
    USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated users can delete sessions" ON course_sessions;
CREATE POLICY "Authenticated users can delete sessions"
    ON course_sessions FOR DELETE
    USING (auth.role() = 'authenticated');

-- ----------------------------------------------------------------------------
-- RLS: applications
-- ----------------------------------------------------------------------------

ALTER TABLE applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own applications" ON applications;
CREATE POLICY "Users can view own applications"
    ON applications FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Authenticated users can insert applications" ON applications;
CREATE POLICY "Authenticated users can insert applications"
    ON applications FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can update own applications" ON applications;
CREATE POLICY "Users can update own applications"
    ON applications FOR UPDATE
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own applications" ON applications;
CREATE POLICY "Users can delete own applications"
    ON applications FOR DELETE
    USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- RLS: leads
-- ----------------------------------------------------------------------------

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can insert leads" ON leads;
CREATE POLICY "Anyone can insert leads"
    ON leads FOR INSERT
    WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Users can view own leads" ON leads;
CREATE POLICY "Users can view own leads"
    ON leads FOR SELECT
    USING (auth.uid() = user_id OR user_id IS NULL);

DROP POLICY IF EXISTS "Users can update own leads" ON leads;
CREATE POLICY "Users can update own leads"
    ON leads FOR UPDATE
    USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- RLS: posts
-- ----------------------------------------------------------------------------

ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view posts" ON posts;
CREATE POLICY "Anyone can view posts"
    ON posts FOR SELECT
    USING (TRUE);

DROP POLICY IF EXISTS "Authenticated users can insert posts" ON posts;
CREATE POLICY "Authenticated users can insert posts"
    ON posts FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authors can update own posts" ON posts;
CREATE POLICY "Authors can update own posts"
    ON posts FOR UPDATE
    USING (auth.uid() = author_id);

DROP POLICY IF EXISTS "Authors can delete own posts" ON posts;
CREATE POLICY "Authors can delete own posts"
    ON posts FOR DELETE
    USING (auth.uid() = author_id);

-- ----------------------------------------------------------------------------
-- RLS: book_orders
-- ----------------------------------------------------------------------------

ALTER TABLE book_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can insert book orders" ON book_orders;
CREATE POLICY "Anyone can insert book orders"
    ON book_orders FOR INSERT
    WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Users can view own book orders" ON book_orders;
CREATE POLICY "Users can view own book orders"
    ON book_orders FOR SELECT
    USING (auth.uid() = user_id OR user_id IS NULL);

DROP POLICY IF EXISTS "Users can update own book orders" ON book_orders;
CREATE POLICY "Users can update own book orders"
    ON book_orders FOR UPDATE
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own book orders" ON book_orders;
CREATE POLICY "Users can delete own book orders"
    ON book_orders FOR DELETE
    USING (auth.uid() = user_id);

-- ============================================================================
-- End of Schema
-- ============================================================================
