-- Enable UUID extension if needed (good practice)
create extension if not exists "uuid-ossp";

-- 1. Create 'leads' table (Contact Forms)
create table if not exists leads (
  id bigint generated by default as identity primary key,
  topic text default 'General Inquiry',
  company text,
  contact_name text not null,
  phone text,
  email text,
  message text,
  password text, -- Added for user management
  status text default 'new', -- new, in_progress, closed
  submitted_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Create 'courses' table (Education Programs)
create table if not exists courses (
  id bigint generated by default as identity primary key,
  title text not null,
  category text, -- Certification, Practical, etc.
  description text,
  price integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Create 'course_sessions' table (Specific Schedules)
create table if not exists course_sessions (
  id bigint generated by default as identity primary key,
  course_id bigint references courses(id),
  start_date date,
  end_date date,
  time_info text, -- e.g. "Sat/Sun 10:00-17:00"
  capacity integer default 20,
  location text,
  status text default 'recruiting', -- recruiting, closed, finished
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Create 'applications' table (Student Enrollments)
create table if not exists applications (
  id bigint generated by default as identity primary key,
  session_id bigint references course_sessions(id),
  applicant_name text not null,
  phone text,
  email text,
  depositor_name text,
  amount integer default 0,
  status text default 'pending_payment', -- pending_payment, paid, cancelled
  memo text,
  submitted_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Create 'posts' table (Resources Board)
create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  author_name text default 'Admin',
  file_url text, -- URL to uploaded file in Supabase Storage
  views integer default 0,
  is_secret boolean default false,
  password text, -- Optional for secret posts
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Grant access to public (anon role) for demo purposes
-- CAUTION: In production, use tighter RLS policies.
alter table leads enable row level security;
create policy "Enable all access for anon" on leads for all using (true) with check (true);

alter table courses enable row level security;
create policy "Enable read access for anon" on courses for select using (true);

alter table course_sessions enable row level security;
create policy "Enable read access for anon" on course_sessions for select using (true);

alter table applications enable row level security;
create policy "Enable insert for anon" on applications for insert with check (true);

alter table posts enable row level security;
create policy "Enable read access for anon" on posts for select using (true);
